version: '3.9'
services:
  api:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    volumes:
      - .:/app
    command: sh -c "python manage.py runserver"
    networks:
      - todolist_default

  migrations:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    env_file:
      - ./.env
    command: sh -c "python manage.py migrate"
    volumes:
      - .:/app
    networks:
      - todolist_default

  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todolist_default

  frontend:
    image: sermalenk/skypro-front:lesson-35
    ports:
      - "80:80"
    depends_on:
      - api
#    volumes:
#       - .:/app
##      - ./nginx.conf:/etc/ngnix/conf.d/default.conf
    networks:
      - todolist_default


volumes:
  pgdata:

networks:
  todolist_default:
    driver: bridge
