version: '3.9'
services:
  api:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres_l33
      POSTGRES_PASSWORD: postgres_l33
      POSTGRES_DB: postgres_l33
    ports:
      - '8001:8000'
    networks:
      - todolist_default

  migrations:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
    networks:
      - todolist_default

  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: postgres_l33
      POSTGRES_PASSWORD: postgres_l33
      POSTGRES_DB: postgres_l33
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todolist_default

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - todolist_default

volumes:
  pgdata:

networks:
  todolist_default:
    driver: bridge
