version: '3.9'
services:
  api:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    networks:
      - todolist_default

  migrations:
    image: dossovmarlen/todolist:latest
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
    volumes:
      - .:/app
    networks:
      - todolist_default

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - todolist_default

  frontend:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - todolist_default

networks:
  todolist_default:
    driver: bridge
