# Generated by Django 4.0.1 on 2023-07-01 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goalcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата дедлайна'),
        ),
    ]
