# Generated by Django 4.0.1 on 2023-07-11 14:40

from django.db import migrations, models




class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_create_new_objects'),
    ]

    operations = [
        migrations.AlterField(
    model_name='goalcategory',
    name='board',
    field=models.ForeignKey(to='goals.Board', verbose_name='Доска', on_delete=models.PROTECT, related_name='categories',

    ),
        ),

    ]
