# Generated by Django 4.0.1 on 2023-07-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal_created_goal_updated_goalcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='goalcomment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='goalcomment',
            name='updated',
        ),
    ]
