# Generated by Django 4.0.1 on 2023-07-03 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_board_boardparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalcomment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
