# Generated by Django 4.0.1 on 2023-07-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_goalcomment_created'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardParticipant',
        ),
    ]
