# Generated by Django 4.0.1 on 2023-07-23 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Телеграм Пользователь', 'verbose_name_plural': 'Телеграм Пользователи'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='telegram_user_id',
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='user',
        ),
        migrations.AddField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(default=0, verbose_name='Чат ID'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='user_id',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='User ID'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Username'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Код подтверждения'),
        ),
    ]
