# Generated by Django 4.0.1 on 2023-07-25 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_tguser_options_remove_tguser_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления'),
        ),
    ]
