version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_todolist
      POSTGRES_PASSWORD: postgres_todolist
      POSTGRES_DB: postgres_todolist
    restart: always
    ports:
    - "5433:5432"

volumes:
  postgres_data: