version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_l33
      POSTGRES_PASSWORD: postgres_l33
      POSTGRES_DB: postgres_l33
    restart: always
    ports:
      - "5432:5432"

volumes:
  postgres_data:
